### ISSUE TITLE
Could you please consider adding jinja template support into table cells by adding this code to render.py

### ISSUE THREAD

**Issue by ateixeirafr** [Thykof/template-pptx-jinja#1]
Hello Thykof,

 Could you please consider adding jinja template support into table cells by adding this code to render.py

    def _render_shape(self, shape):
        if shape.has_text_frame:
            self._render_text_frame(shape.text_frame)
        if shape.has_table:
            self._render_table(shape.table) 
        if shape.shape_type == MSO_SHAPE_TYPE.PICTURE:
            self._render_picture(shape)

    def _render_table(self, table):
        for cell in table.iter_cells(): 
            self._render_cell(cell)

    def _render_cell(self, cell):
        self._render_text_frame(cell.text_frame)

Regards

**Comment by Thykof** [comment]
Hello ateixeirafr,

Thank you for your contribution.

I have pushed into develop a commit that adds support for table cells.

Please can you test and tell me if it is good for you, then I will push to master and publish a new version to PyPI.

**Comment by ateixeirafr** [comment]
Hello Nathan,

It Works like a charm !

Thank you.

Regards.

If I have time this week, I'll try to manage also charts

Le dim. 8 août 2021 à 09:29, Nathan Seva ***@***.***> a
écrit :
