### ISSUE TITLE
'SlidePart' object has no attribute 'related_parts'

### ISSUE THREAD

**Issue by hilarex** [Thykof/template-pptx-jinja#5]
Hello ! I have another issue right after cloning your repo and running python3 example.py. I just did "git clone", then "python3 example.py". I tried on Ubuntu 2021.

```python
Traceback (most recent call last):
  File "/tmp/template-pptx-jinja/example.py", line 47, in <module>
    main()
  File "/tmp/template-pptx-jinja/example.py", line 43, in main
    message = rendering.process()
  File "/tmp/template-pptx-jinja/template_pptx_jinja/render.py", line 36, in process
    self._render_slide(slide)
  File "/tmp/template-pptx-jinja/template_pptx_jinja/render.py", line 43, in _render_slide
    self._render_shape(shape)
  File "/tmp/template-pptx-jinja/template_pptx_jinja/render.py", line 51, in _render_shape
    self._render_picture(shape)
  File "/tmp/template-pptx-jinja/template_pptx_jinja/render.py", line 56, in _render_picture
    pictures.replace_img_slide(
  File "/tmp/template-pptx-jinja/template_pptx_jinja/pictures.py", line 19, in replace_img_slide
    imgPart = slide.part.related_parts[imgRID]
AttributeError: 'SlidePart' object has no attribute 'related_parts'
```

**Comment by Thykof** [comment]
Hello,

Please run this before `python3 example.py`:

    python3 -m venv env
    source env/bin/activate
    pip install -r requirements.txt

and tell me if it change somthing

**Comment by hilarex** [comment]
No, still the same error

**Comment by hilarex** [comment]
Can this be the reason : https://giters.com/scanny/python-pptx/issues/761 ?

**Comment by Thykof** [comment]
it may, but I can't reproduce your error, are you running `python3 example.py` inside the virtual environment. Go inside with `source env/bin/activate` and please provide me with the output of `python --version`

**Comment by hilarex** [comment]
Yes I'm inside a virtual environment, I tried on two different machine. Python version return : Python 3.8.9

**Comment by ThomFri** [comment]
Try this instead (I'm not sure if it really does the same but it works for me if I want to replace images ;) )

`slide.part.related_part(imgRID)`

**Comment by pygumby** [comment]
@Thykof, first off, thank you for creating `template-pptx-jinja` — it seems perfect for our use case. Sadly, we're running into the exact same issue. As ThomFri has provided the fix already, would you be willing to adapt line 19 of the `pictures.py` file accordingly and publish a fixed version? That would be super helpful. I can also do it and create a pull request, if you'd like that more. Thank you so much! (Some background information can be found here: https://stackoverflow.com/questions/70159390/python-pptx-library-issue-replacing-image-in-slides-slidepart-object-has-no)

**Comment by Thykof** [comment]
Hi @typeduke I'm glad this lib fit your needs! Feel free to open a pull request. I'll try to publish a new version on pypi.

**Comment by Thykof** [comment]
@typeduke I have just released https://pypi.org/project/template-pptx-jinja/0.2.1 with the fix proposed by @ThomFri. Thank you both for contributing ;)
